version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: tushikane-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tushikane
    networks:
      - tushikane-net

  backend:
    build: ./backend
    container_name: tushikane-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tushikane
      - PORT=5000
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - tushikane-net

networks:
  tushikane-net:
    driver: bridge

volumes:
  mongodb_data:
