name: Deploy Backend to Render & Frontend to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Backend Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}
      - name: Trigger Vercel Frontend Deploy
        run: |
          curl -X POST ${{ secrets.VERCEL_FRONTEND_DEPLOY_HOOK }} 